function [time_neuropil_back, time_neuropil_back_SNR, time_neuropil_back_NoRM, snr_f_avg_back, snr_f_avg_neuropil_back, snr_f_avg_back_SNR, snr_f_avg_neuropil_back_SNR, snr_f_avg_back_NoRM, snr_f_avg_neuropil_back_NoRM, snr_ca_avg_back, snr_ca_avg_neuropil_back, snr_ca_avg_back_SNR, snr_ca_avg_neuropil_back_SNR, snr_ca_avg_back_NoRM, snr_ca_avg_neuropil_back_NoRM, corr_f_avg_back, corr_f_avg_neuropil_back, corr_f_avg_back_SNR, corr_f_avg_neuropil_back_SNR, corr_f_avg_back_NoRM, corr_f_avg_neuropil_back_NoRM, corr_ca_avg_back, corr_ca_avg_neuropil_back, corr_ca_avg_back_SNR, corr_ca_avg_neuropil_back_SNR, corr_ca_avg_back_NoRM, corr_ca_avg_neuropil_back_NoRM] = import_neuropil_withback_analyses(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIME_NEUROPIL_BACK, TIME_NEUROPIL_BACK_SNR, TIME_NEUROPIL_BACK_NORM,
%  SNR_F_AVG_BACK, SNR_F_AVG_NEUROPIL_BACK, SNR_F_AVG_BACK_SNR,
%  SNR_F_AVG_NEUROPIL_BACK_SNR, SNR_F_AVG_BACK_NORM,
%  SNR_F_AVG_NEUROPIL_BACK_NORM, SNR_CA_AVG_BACK,
%  SNR_CA_AVG_NEUROPIL_BACK, SNR_CA_AVG_BACK_SNR,
%  SNR_CA_AVG_NEUROPIL_BACK_SNR, SNR_CA_AVG_BACK_NORM,
%  SNR_CA_AVG_NEUROPIL_BACK_NORM, CORR_F_AVG_BACK,
%  CORR_F_AVG_NEUROPIL_BACK, CORR_F_AVG_BACK_SNR,
%  CORR_F_AVG_NEUROPIL_BACK_SNR, CORR_F_AVG_BACK_NORM,
%  CORR_F_AVG_NEUROPIL_BACK_NORM, CORR_CA_AVG_BACK,
%  CORR_CA_AVG_NEUROPIL_BACK, CORR_CA_AVG_BACK_SNR,
%  CORR_CA_AVG_NEUROPIL_BACK_SNR, CORR_CA_AVG_BACK_NORM,
%  CORR_CA_AVG_NEUROPIL_BACK_NORM] = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as column vectors.
%
%  [TIME_NEUROPIL_BACK, TIME_NEUROPIL_BACK_SNR, TIME_NEUROPIL_BACK_NORM,
%  SNR_F_AVG_BACK, SNR_F_AVG_NEUROPIL_BACK, SNR_F_AVG_BACK_SNR,
%  SNR_F_AVG_NEUROPIL_BACK_SNR, SNR_F_AVG_BACK_NORM,
%  SNR_F_AVG_NEUROPIL_BACK_NORM, SNR_CA_AVG_BACK,
%  SNR_CA_AVG_NEUROPIL_BACK, SNR_CA_AVG_BACK_SNR,
%  SNR_CA_AVG_NEUROPIL_BACK_SNR, SNR_CA_AVG_BACK_NORM,
%  SNR_CA_AVG_NEUROPIL_BACK_NORM, CORR_F_AVG_BACK,
%  CORR_F_AVG_NEUROPIL_BACK, CORR_F_AVG_BACK_SNR,
%  CORR_F_AVG_NEUROPIL_BACK_SNR, CORR_F_AVG_BACK_NORM,
%  CORR_F_AVG_NEUROPIL_BACK_NORM, CORR_CA_AVG_BACK,
%  CORR_CA_AVG_NEUROPIL_BACK, CORR_CA_AVG_BACK_SNR,
%  CORR_CA_AVG_NEUROPIL_BACK_SNR, CORR_CA_AVG_BACK_NORM,
%  CORR_CA_AVG_NEUROPIL_BACK_NORM] = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [time_neuropil_back, time_neuropil_back_SNR, time_neuropil_back_NoRM, snr_f_avg_back, snr_f_avg_neuropil_back, snr_f_avg_back_SNR, snr_f_avg_neuropil_back_SNR, snr_f_avg_back_NoRM, snr_f_avg_neuropil_back_NoRM, snr_ca_avg_back, snr_ca_avg_neuropil_back, snr_ca_avg_back_SNR, snr_ca_avg_neuropil_back_SNR, snr_ca_avg_back_NoRM, snr_ca_avg_neuropil_back_NoRM, corr_f_avg_back, corr_f_avg_neuropil_back, corr_f_avg_back_SNR, corr_f_avg_neuropil_back_SNR, corr_f_avg_back_NoRM, corr_f_avg_neuropil_back_NoRM, corr_ca_avg_back, corr_ca_avg_neuropil_back, corr_ca_avg_back_SNR, corr_ca_avg_neuropil_back_SNR, corr_ca_avg_back_NoRM, corr_ca_avg_neuropil_back_NoRM] = importfile("/media/DATA/mmoroni/software_sls_project/analyses/anesthetized_withback_neuropil_summary.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-May-2020 10:19:22

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 27);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time_neuropil_back", "time_neuropil_back_SNR", "time_neuropil_back_NoRM", "snr_f_avg_back", "snr_f_avg_neuropil_back", "snr_f_avg_back_SNR", "snr_f_avg_neuropil_back_SNR", "snr_f_avg_back_NoRM", "snr_f_avg_neuropil_back_NoRM", "snr_ca_avg_back", "snr_ca_avg_neuropil_back", "snr_ca_avg_back_SNR", "snr_ca_avg_neuropil_back_SNR", "snr_ca_avg_back_NoRM", "snr_ca_avg_neuropil_back_NoRM", "corr_f_avg_back", "corr_f_avg_neuropil_back", "corr_f_avg_back_SNR", "corr_f_avg_neuropil_back_SNR", "corr_f_avg_back_NoRM", "corr_f_avg_neuropil_back_NoRM", "corr_ca_avg_back", "corr_ca_avg_neuropil_back", "corr_ca_avg_back_SNR", "corr_ca_avg_neuropil_back_SNR", "corr_ca_avg_back_NoRM", "corr_ca_avg_neuropil_back_NoRM"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
time_neuropil_back = tbl.time_neuropil_back;
time_neuropil_back_SNR = tbl.time_neuropil_back_SNR;
time_neuropil_back_NoRM = tbl.time_neuropil_back_NoRM;
snr_f_avg_back = tbl.snr_f_avg_back;
snr_f_avg_neuropil_back = tbl.snr_f_avg_neuropil_back;
snr_f_avg_back_SNR = tbl.snr_f_avg_back_SNR;
snr_f_avg_neuropil_back_SNR = tbl.snr_f_avg_neuropil_back_SNR;
snr_f_avg_back_NoRM = tbl.snr_f_avg_back_NoRM;
snr_f_avg_neuropil_back_NoRM = tbl.snr_f_avg_neuropil_back_NoRM;
snr_ca_avg_back = tbl.snr_ca_avg_back;
snr_ca_avg_neuropil_back = tbl.snr_ca_avg_neuropil_back;
snr_ca_avg_back_SNR = tbl.snr_ca_avg_back_SNR;
snr_ca_avg_neuropil_back_SNR = tbl.snr_ca_avg_neuropil_back_SNR;
snr_ca_avg_back_NoRM = tbl.snr_ca_avg_back_NoRM;
snr_ca_avg_neuropil_back_NoRM = tbl.snr_ca_avg_neuropil_back_NoRM;
corr_f_avg_back = tbl.corr_f_avg_back;
corr_f_avg_neuropil_back = tbl.corr_f_avg_neuropil_back;
corr_f_avg_back_SNR = tbl.corr_f_avg_back_SNR;
corr_f_avg_neuropil_back_SNR = tbl.corr_f_avg_neuropil_back_SNR;
corr_f_avg_back_NoRM = tbl.corr_f_avg_back_NoRM;
corr_f_avg_neuropil_back_NoRM = tbl.corr_f_avg_neuropil_back_NoRM;
corr_ca_avg_back = tbl.corr_ca_avg_back;
corr_ca_avg_neuropil_back = tbl.corr_ca_avg_neuropil_back;
corr_ca_avg_back_SNR = tbl.corr_ca_avg_back_SNR;
corr_ca_avg_neuropil_back_SNR = tbl.corr_ca_avg_neuropil_back_SNR;
corr_ca_avg_back_NoRM = tbl.corr_ca_avg_back_NoRM;
corr_ca_avg_neuropil_back_NoRM = tbl.corr_ca_avg_neuropil_back_NoRM;
end