save_path_0 = '/media/DATA/mmoroni/software_sls_project/analyses/';
%% initialize data
csv_data = '../data/data_table_server.csv';
data_surround_0 = readmatrix(csv_data,'Range','F:F','OutputType','double');
animal_state_0 = readmatrix(csv_data,'Range','B:B','OutputType','string');
ref_ROIs_0 = readmatrix(csv_data,'Range','I:I','OutputType','string');

anesthetized = 1; %flag to analyze awake/anesthetized animals data
%filter data
if anesthetized == 1
    id_keep = find(animal_state_0 == 'anesthetized/');
    save_path = [save_path_0 'anesthetized/'];
else
    id_keep = find(animal_state_0 == 'awake/');
    save_path = [save_path_0 'awake/'];
end
data_surround = data_surround_0(id_keep);
ref_ROIs = ref_ROIs_0(id_keep);

%keep only with reference segmentation
id_keep2 = find(1-ismissing(ref_ROIs));
data_surround = data_surround(id_keep2);

%%
if anesthetized == 1
    id_keep_def = [1 4 5 11 17 26 27 32 33 34 35 37 40 42 45 46 47 48 49 148 149 ...
        150 151 152 153 154 155 156 157 158 159 160 164 167 171 172 175 176 177 ...
        178 180 181 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 ...
        204 205 206 207 208 209 210 211 212 213 214 215 216 223 226 228 229 235 ...
        245 246 247 250 251 252 253 254 255 256];
else
    id_keep_def = [6 12 13 22 23 24 25 26 27 28]; %awake
end
down_rate = [0.1 1 Inf];

%% import analyses results

if anesthetized == 1
    [time_neuropil_noback,time_neuropil_noback_SNR,time_neuropil_noback_NoRM_01,...
        time_neuropil_noback_NoRM_1,time_neuropil_noback_NoRM,snr_f_avg_noback,...
        snr_f_avg_neuropil_noback, snr_f_avg_noback_SNR,snr_f_avg_neuropil_noback_SNR,...
        snr_f_avg_noback_NoRM_01,snr_f_avg_noback_NoRM_1, snr_f_avg_noback_NoRM,...
        snr_f_avg_neuropil_noback_NoRM_01, snr_f_avg_neuropil_noback_NoRM_1,...
        snr_f_avg_neuropil_noback_NoRM, snr_ca_avg_noback,snr_ca_avg_neuropil_noback,...
        snr_ca_avg_noback_SNR,snr_ca_avg_neuropil_noback_SNR, snr_ca_avg_noback_NoRM_01,...
        snr_ca_avg_noback_NoRM_1,snr_ca_avg_noback_NoRM,snr_ca_avg_neuropil_noback_NoRM_01,...
        snr_ca_avg_neuropil_noback_NoRM_1,snr_ca_avg_neuropil_noback_NoRM,...
        corr_f_avg_raw,corr_f_avg_noback,corr_f_avg_neuropil_noback,...
        corr_f_avg_noback_SNR,corr_f_avg_neuropil_noback_SNR,corr_f_avg_noback_NoRM_01,...
        corr_f_avg_noback_NoRM_1,corr_f_avg_noback_NoRM,corr_f_avg_neuropil_noback_NoRM_01,...
        corr_f_avg_neuropil_noback_NoRM_1,corr_f_avg_neuropil_noback_NoRM,corr_ca_avg_raw,...
        corr_ca_avg_noback,corr_ca_avg_neuropil_noback, corr_ca_avg_noback_SNR,...
        corr_ca_avg_neuropil_noback_SNR, corr_ca_avg_noback_NoRM_01,corr_ca_avg_noback_NoRM_1,...
        corr_ca_avg_noback_NoRM,corr_ca_avg_neuropil_noback_NoRM_01,...
        corr_ca_avg_neuropil_noback_NoRM_1,corr_ca_avg_neuropil_noback_NoRM] =...
        import_neuropil_analyses_diff_rate([save_path_0 'anesthetized_neuropil_summary_diff_rate.csv']);
    
    
    [time_neuropil_back, time_neuropil_back_SNR, time_neuropil_back_NoRM_01,...
    time_neuropil_back_NoRM_1, time_neuropil_back_NoRM, snr_f_avg_raw,...
    snr_f_avg_neuropil_back, snr_f_avg_back_SNR, snr_f_avg_neuropil_back_SNR,...
    snr_f_avg_back_NoRM_01, snr_f_avg_back_NoRM_1, snr_f_avg_back_NoRM, ...
    snr_f_avg_neuropil_back_NoRM_01, snr_f_avg_neuropil_back_NoRM_1,...
    snr_f_avg_neuropil_back_NoRM, snr_ca_avg_raw, snr_ca_avg_neuropil_back,...
    snr_ca_avg_back_SNR, snr_ca_avg_neuropil_back_SNR, snr_ca_avg_back_NoRM_01,...
    snr_ca_avg_back_NoRM_1, snr_ca_avg_back_NoRM, snr_ca_avg_neuropil_back_NoRM_01,...
    snr_ca_avg_neuropil_back_NoRM_1, snr_ca_avg_neuropil_back_NoRM, ...
    corr_f_avg_raw, corr_f_avg_neuropil_back, corr_f_avg_back_SNR,...
    corr_f_avg_neuropil_back_SNR, corr_f_avg_back_NoRM_01, corr_f_avg_back_NoRM_1,...
    corr_f_avg_back_NoRM, corr_f_avg_neuropil_back_NoRM_01,...
    corr_f_avg_neuropil_back_NoRM_1, corr_f_avg_neuropil_back_NoRM,...
    corr_ca_avg_raw, corr_ca_avg_neuropil_back, corr_ca_avg_back_SNR,...
    corr_ca_avg_neuropil_back_SNR, corr_ca_avg_back_NoRM_01, corr_ca_avg_back_NoRM_1,...
    corr_ca_avg_back_NoRM, corr_ca_avg_neuropil_back_NoRM_01,...
    corr_ca_avg_neuropil_back_NoRM_1, corr_ca_avg_neuropil_back_NoRM] = ...
    import_neuropil_analyses_withback_diff_rate([save_path_0 'anesthetized_neuropil_withback_summary_diff_rate.csv']);
else
     [time_neuropil_noback,time_neuropil_noback_SNR,time_neuropil_noback_NoRM_01,...
        time_neuropil_noback_NoRM_1,time_neuropil_noback_NoRM,snr_f_avg_noback,...
        snr_f_avg_neuropil_noback, snr_f_avg_noback_SNR,snr_f_avg_neuropil_noback_SNR,...
        snr_f_avg_noback_NoRM_01,snr_f_avg_noback_NoRM_1, snr_f_avg_noback_NoRM,...
        snr_f_avg_neuropil_noback_NoRM_01, snr_f_avg_neuropil_noback_NoRM_1,...
        snr_f_avg_neuropil_noback_NoRM, snr_ca_avg_noback,snr_ca_avg_neuropil_noback,...
        snr_ca_avg_noback_SNR,snr_ca_avg_neuropil_noback_SNR, snr_ca_avg_noback_NoRM_01,...
        snr_ca_avg_noback_NoRM_1,snr_ca_avg_noback_NoRM,snr_ca_avg_neuropil_noback_NoRM_01,...
        snr_ca_avg_neuropil_noback_NoRM_1,snr_ca_avg_neuropil_noback_NoRM,...
        corr_f_avg_raw,corr_f_avg_noback,corr_f_avg_neuropil_noback,...
        corr_f_avg_noback_SNR,corr_f_avg_neuropil_noback_SNR,corr_f_avg_noback_NoRM_01,...
        corr_f_avg_noback_NoRM_1,corr_f_avg_noback_NoRM,corr_f_avg_neuropil_noback_NoRM_01,...
        corr_f_avg_neuropil_noback_NoRM_1,corr_f_avg_neuropil_noback_NoRM,corr_ca_avg_raw,...
        corr_ca_avg_noback,corr_ca_avg_neuropil_noback, corr_ca_avg_noback_SNR,...
        corr_ca_avg_neuropil_noback_SNR, corr_ca_avg_noback_NoRM_01,corr_ca_avg_noback_NoRM_1,...
        corr_ca_avg_noback_NoRM,corr_ca_avg_neuropil_noback_NoRM_01,...
        corr_ca_avg_neuropil_noback_NoRM_1,corr_ca_avg_neuropil_noback_NoRM] =...
        import_neuropil_analyses_diff_rate([save_path_0 'awake_neuropil_summary_diff_rate.csv']);
    
    
    [time_neuropil_back, time_neuropil_back_SNR, time_neuropil_back_NoRM_01,...
    time_neuropil_back_NoRM_1, time_neuropil_back_NoRM, snr_f_avg_raw,...
    snr_f_avg_neuropil_back, snr_f_avg_back_SNR, snr_f_avg_neuropil_back_SNR,...
    snr_f_avg_back_NoRM_01, snr_f_avg_back_NoRM_1, snr_f_avg_back_NoRM, ...
    snr_f_avg_neuropil_back_NoRM_01, snr_f_avg_neuropil_back_NoRM_1,...
    snr_f_avg_neuropil_back_NoRM, snr_ca_avg_raw, snr_ca_avg_neuropil_back,...
    snr_ca_avg_back_SNR, snr_ca_avg_neuropil_back_SNR, snr_ca_avg_back_NoRM_01,...
    snr_ca_avg_back_NoRM_1, snr_ca_avg_back_NoRM, snr_ca_avg_neuropil_back_NoRM_01,...
    snr_ca_avg_neuropil_back_NoRM_1, snr_ca_avg_neuropil_back_NoRM, ...
    corr_f_avg_raw, corr_f_avg_neuropil_back, corr_f_avg_back_SNR,...
    corr_f_avg_neuropil_back_SNR, corr_f_avg_back_NoRM_01, corr_f_avg_back_NoRM_1,...
    corr_f_avg_back_NoRM, corr_f_avg_neuropil_back_NoRM_01,...
    corr_f_avg_neuropil_back_NoRM_1, corr_f_avg_neuropil_back_NoRM,...
    corr_ca_avg_raw, corr_ca_avg_neuropil_back, corr_ca_avg_back_SNR,...
    corr_ca_avg_neuropil_back_SNR, corr_ca_avg_back_NoRM_01, corr_ca_avg_back_NoRM_1,...
    corr_ca_avg_back_NoRM, corr_ca_avg_neuropil_back_NoRM_01,...
    corr_ca_avg_neuropil_back_NoRM_1, corr_ca_avg_neuropil_back_NoRM] = ...
    import_neuropil_analyses_withback_diff_rate([save_path_0 'awake_neuropil_withback_summary_diff_rate.csv']);
end


%%
data_surround = data_surround(id_keep_def);
%%
data_surround(data_surround>=2)=2;
data_surround(data_surround<=1)=1;
%%
box_plot_snr = figure; 
% multcmp_snr = figure; 
surr_array = unique(data_surround);
for i_s = 1:length(surr_array)
    snr_f_raw_temp = snr_f_avg_raw(find(data_surround==surr_array(i_s)));
    snr_f_raw_neuropil_temp = snr_f_avg_neuropil_back(find(data_surround==surr_array(i_s)));
    snr_f_raw_SNR_temp = snr_f_avg_back_SNR(find(data_surround==surr_array(i_s)));
    snr_f_raw_SNR_neuropil_temp = snr_f_avg_neuropil_back_SNR(find(data_surround==surr_array(i_s)));
    snr_f_raw_NoRM01_temp = snr_f_avg_back_NoRM_01(find(data_surround==surr_array(i_s)));
    snr_f_raw_NoRM1_temp = snr_f_avg_back_NoRM_1(find(data_surround==surr_array(i_s)));
    snr_f_raw_NoRM_temp = snr_f_avg_back_NoRM(find(data_surround==surr_array(i_s)));
    snr_f_raw_NoRM01_neuropil_temp = snr_f_avg_neuropil_back_NoRM_01(find(data_surround==surr_array(i_s)));
    snr_f_raw_NoRM1_neuropil_temp = snr_f_avg_neuropil_back_NoRM_1(find(data_surround==surr_array(i_s)));
    snr_f_raw_NoRM_neuropil_temp = snr_f_avg_neuropil_back_NoRM(find(data_surround==surr_array(i_s)));
    snr_f_noback_temp = snr_f_avg_noback(find(data_surround==surr_array(i_s)));
    snr_f_noback_neuropil_temp = snr_f_avg_neuropil_noback(find(data_surround==surr_array(i_s)));
    snr_f_noback_SNR_temp = snr_f_avg_noback_SNR(find(data_surround==surr_array(i_s)));
    snr_f_noback_SNR_neuropil_temp = snr_f_avg_neuropil_noback_SNR(find(data_surround==surr_array(i_s)));
    snr_f_noback_NoRM01_temp = snr_f_avg_noback_NoRM_01(find(data_surround==surr_array(i_s)));
    snr_f_noback_NoRM1_temp = snr_f_avg_noback_NoRM_1(find(data_surround==surr_array(i_s)));
    snr_f_noback_NoRM_temp = snr_f_avg_noback_NoRM(find(data_surround==surr_array(i_s)));
    snr_f_noback_NoRM01_neuropil_temp = snr_f_avg_neuropil_noback_NoRM_01(find(data_surround==surr_array(i_s)));
    snr_f_noback_NoRM1_neuropil_temp = snr_f_avg_neuropil_noback_NoRM_1(find(data_surround==surr_array(i_s)));
    snr_f_noback_NoRM_neuropil_temp = snr_f_avg_neuropil_noback_NoRM(find(data_surround==surr_array(i_s)));

    %     snr_ca_noback_temp = snr_ca_avg_noback(find(data_surround==data_surround(i_s)));
%     snr_ca_SNR_temp = snr_ca_avg_SNR(find(data_surround==data_surround(i_s)));
%     snr_ca_NoRM_temp = snr_ca_avg_NoRM(find(data_surround==data_surround(i_s)));
    figure(box_plot_snr)
    subplot(2,1,i_s);
    hold on; boxplot([snr_f_raw_temp(:), snr_f_noback_temp(:), snr_f_raw_neuropil_temp(:), ...
        snr_f_noback_SNR_temp(:), snr_f_noback_NoRM01_temp(:), snr_f_noback_NoRM1_temp(:),...
        snr_f_noback_NoRM_temp(:),snr_f_raw_SNR_temp(:),snr_f_raw_NoRM01_temp(:),snr_f_raw_NoRM1_temp(:),...
        snr_f_raw_NoRM_temp(:), snr_f_noback_SNR_neuropil_temp(:), snr_f_noback_NoRM01_neuropil_temp(:),...
        snr_f_noback_NoRM1_neuropil_temp(:),snr_f_noback_NoRM_neuropil_temp(:),...
        snr_f_raw_SNR_neuropil_temp(:), snr_f_raw_NoRM01_neuropil_temp(:),...
        snr_f_raw_NoRM1_neuropil_temp(:),snr_f_raw_NoRM_neuropil_temp(:),snr_f_noback_neuropil_temp(:)],...
        'Labels',{'raw','no back','no neuropil','no back, SNR','no back, NoRM01',...
        'no back, NoRM1','no back, NoRM','raw, SNR','raw, NoRM01','raw, NoRM1',...
        'raw, NoRM', 'no back, SNR, no neuropil', 'no back, NoRM01, no neuropil',...
        'no back, NoRM1, no neuropil','no back, NoRM, no neuropil',...
        'raw, SNR, no neuropil', 'raw, NoRM01, no neuropil','raw, NoRM1, no neuropil',...
        'raw, NoRM, no neuropil','no back, no neuropil'},...
        'PlotStyle','traditional','orientation','horizontal','DataLim',[0 80]);
    ylabel('SNR fluo');
    title(['surround=' num2str(surr_array(i_s))]);
    [p,tbl,stats] = kruskalwallis([snr_f_raw_temp(:), snr_f_noback_temp(:), snr_f_raw_neuropil_temp(:), ...
    snr_f_noback_SNR_temp(:), snr_f_noback_NoRM01_temp(:), snr_f_noback_NoRM1_temp(:),...
    snr_f_noback_NoRM_temp(:), snr_f_raw_SNR_temp(:),snr_f_raw_NoRM01_temp(:),snr_f_raw_NoRM1_temp(:),...
    snr_f_raw_NoRM_temp(:), snr_f_noback_SNR_neuropil_temp(:), snr_f_noback_NoRM01_neuropil_temp(:),...
    snr_f_noback_NoRM1_neuropil_temp(:),snr_f_noback_NoRM_neuropil_temp(:),...
    snr_f_raw_SNR_neuropil_temp(:), snr_f_raw_NoRM01_neuropil_temp(:),...
    snr_f_raw_NoRM1_neuropil_temp(:),snr_f_raw_NoRM_neuropil_temp(:),snr_f_noback_neuropil_temp(:)],...
    {'raw','no back','no neuropil','no back, SNR','no back, NoRM01','no back, NoRM1',...
    'no back, NoRM','raw, SNR','raw, NoRM01','raw, NoRM1','raw, NoRM', ...
    'no back, SNR, no neuropil', 'no back, NoRM01, no neuropil',...
    'no back, NoRM1, no neuropil','no back, NoRM, no neuropil',...
    'raw, SNR, no neuropil', 'raw, NoRM01, no neuropil','raw, NoRM1, no neuropil',...
    'raw, NoRM, no neuropil','no back, no neuropil'});
%     figure(multcmp_snr)
%     subplot(2,2,i_s);
%     hold on; 
    figure;
    c = multcompare(stats);
    title(['SNR. surround=' num2str(surr_array(i_s))]);
end


%%
box_plot_corr = figure; 
surr_array = unique(data_surround);
for i_s = 1:length(surr_array)
    corr_f_raw_temp = corr_f_avg_raw(find(data_surround==surr_array(i_s)));
    corr_f_raw_neuropil_temp = corr_f_avg_neuropil_back(find(data_surround==surr_array(i_s)));
    corr_f_raw_SNR_temp = corr_f_avg_back_SNR(find(data_surround==surr_array(i_s)));
    corr_f_raw_SNR_neuropil_temp = corr_f_avg_neuropil_back_SNR(find(data_surround==surr_array(i_s)));
    corr_f_raw_NoRM01_temp = corr_f_avg_back_NoRM_01(find(data_surround==surr_array(i_s)));
    corr_f_raw_NoRM1_temp = corr_f_avg_back_NoRM_1(find(data_surround==surr_array(i_s)));
    corr_f_raw_NoRM_temp = corr_f_avg_back_NoRM(find(data_surround==surr_array(i_s)));
    corr_f_raw_NoRM01_neuropil_temp = corr_f_avg_neuropil_back_NoRM_01(find(data_surround==surr_array(i_s)));
    corr_f_raw_NoRM1_neuropil_temp = corr_f_avg_neuropil_back_NoRM_1(find(data_surround==surr_array(i_s)));
    corr_f_raw_NoRM_neuropil_temp = corr_f_avg_neuropil_back_NoRM(find(data_surround==surr_array(i_s)));
    corr_f_noback_temp = corr_f_avg_noback(find(data_surround==surr_array(i_s)));
    corr_f_noback_neuropil_temp = corr_f_avg_neuropil_noback(find(data_surround==surr_array(i_s)));
    corr_f_noback_SNR_temp = corr_f_avg_noback_SNR(find(data_surround==surr_array(i_s)));
    corr_f_noback_SNR_neuropil_temp = corr_f_avg_neuropil_noback_SNR(find(data_surround==surr_array(i_s)));
    corr_f_noback_NoRM01_temp = corr_f_avg_noback_NoRM_01(find(data_surround==surr_array(i_s)));
    corr_f_noback_NoRM1_temp = corr_f_avg_noback_NoRM_1(find(data_surround==surr_array(i_s)));
    corr_f_noback_NoRM_temp = corr_f_avg_noback_NoRM(find(data_surround==surr_array(i_s)));
    corr_f_noback_NoRM01_neuropil_temp = corr_f_avg_neuropil_noback_NoRM_01(find(data_surround==surr_array(i_s)));
    corr_f_noback_NoRM1_neuropil_temp = corr_f_avg_neuropil_noback_NoRM_1(find(data_surround==surr_array(i_s)));
    corr_f_noback_NoRM_neuropil_temp = corr_f_avg_neuropil_noback_NoRM(find(data_surround==surr_array(i_s)));
%     snr_ca_noback_temp = snr_ca_avg_noback(find(data_surround==data_surround(i_s)));
%     snr_ca_SNR_temp = snr_ca_avg_SNR(find(data_surround==data_surround(i_s)));
%     snr_ca_NoRM_temp = snr_ca_avg_NoRM(find(data_surround==data_surround(i_s)));
figure(box_plot_corr);    
subplot(2,1,i_s);
    hold on; boxplot([corr_f_raw_temp(:), corr_f_noback_temp(:), corr_f_raw_neuropil_temp(:), ...
        corr_f_noback_SNR_temp(:), corr_f_noback_NoRM01_temp(:), corr_f_noback_NoRM1_temp(:),...
        corr_f_noback_NoRM_temp(:), corr_f_raw_SNR_temp(:),corr_f_raw_NoRM01_temp(:),corr_f_raw_NoRM1_temp(:),...
        corr_f_raw_NoRM_temp(:),corr_f_noback_SNR_neuropil_temp(:),corr_f_noback_NoRM01_neuropil_temp(:),...
        corr_f_noback_NoRM1_neuropil_temp(:),corr_f_noback_NoRM_neuropil_temp(:),...
        corr_f_raw_SNR_neuropil_temp(:), corr_f_raw_NoRM01_neuropil_temp(:),...
        corr_f_raw_NoRM1_neuropil_temp(:),corr_f_raw_NoRM_neuropil_temp(:),corr_f_noback_neuropil_temp(:)],...
        'Labels',{'raw','no back','no neuropil','no back, SNR','no back, NoRM01',...
        'no back, NoRM1','no back, NoRM', 'raw, SNR','raw, NoRM01','raw, NoRM1',...
        'raw, NoRM', 'no back, SNR, no neuropil', 'no back, NoRM01, no neuropil',...
        'no back, NoRM1, no neuropil','no back, NoRM, no neuropil','raw, SNR, no neuropil',...
        'raw, NoRM01, no neuropil','raw, NoRM1, no neuropil','raw, NoRM, no neuropil',...
        'no back, no neuropil'},...
        'PlotStyle','traditional','orientation','horizontal','DataLim',[0 1]);
    ylabel('corr fluo');
    title(['surround=' num2str(surr_array(i_s))]);
    [p,tbl,stats] = kruskalwallis([corr_f_raw_temp(:), corr_f_noback_temp(:), corr_f_raw_neuropil_temp(:), ...
    corr_f_noback_SNR_temp(:), corr_f_noback_NoRM01_temp(:), corr_f_noback_NoRM1_temp(:), ...
    corr_f_noback_NoRM_temp(:), corr_f_raw_SNR_temp(:),corr_f_raw_NoRM01_temp(:),corr_f_raw_NoRM1_temp(:),...
    corr_f_raw_NoRM_temp(:), corr_f_noback_SNR_neuropil_temp(:), corr_f_noback_NoRM01_neuropil_temp(:),...
    corr_f_noback_NoRM1_neuropil_temp(:),corr_f_noback_NoRM_neuropil_temp(:),...
    corr_f_raw_SNR_neuropil_temp(:), corr_f_raw_NoRM01_neuropil_temp(:),corr_f_raw_NoRM1_neuropil_temp(:),...
    corr_f_raw_NoRM_neuropil_temp(:),corr_f_noback_neuropil_temp(:)],...
    {'raw','no back','no neuropil','no back, SNR','no back, NoRM01','no back, NoRM1',...
    'no back, NoRM', 'raw, SNR','raw, NoRM01','raw, NoRM1','raw, NoRM', ...
    'no back, SNR, no neuropil', 'no back, NoRM01, no neuropil','no back, NoRM1, no neuropil',...
    'no back, NoRM, no neuropil','raw, SNR, no neuropil', 'raw, NoRM01, no neuropil',...
    'raw, NoRM1, no neuropil','raw, NoRM, no neuropil','no back, no neuropil'});
    figure;
    c = multcompare(stats);
    title(['CORR. surround=' num2str(surr_array(i_s))]);
end

% [mean_snr, std_snr, numel_snr] = grpstats([corr_f_raw_temp(:), corr_f_noback_temp(:), corr_f_raw_neuropil_temp(:), ...
%     corr_f_noback_SNR_temp(:), corr_f_noback_NoRM_temp(:), corr_f_raw_SNR_temp(:),...
%     corr_f_raw_NoRM_temp(:), corr_f_noback_SNR_neuropil_temp(:), corr_f_noback_NoRM_neuropil_temp(:),...
%     corr_f_raw_SNR_neuropil_temp(:), corr_f_raw_NoRM_neuropil_temp(:), corr_f_nobak_neuropil_temp(:)],...
%     'Labels',{'raw','no back','no neuropil','no back, SNR','no back, NoRM', 'raw, SNR',...
%     'raw, NoRM', 'no back, SNR, no neuropil', 'no back, NoRM, no neuropil',...
%     'raw, SNR, no neuropil', 'raw, NoRM, no neuropil', 'no back, no neuropil'},...
%     {'mean','std','numel'});
% [p,tbl,stats] = kruskalwallis([corr_f_raw_temp(:), corr_f_noback_temp(:), corr_f_raw_neuropil_temp(:), ...
%     corr_f_noback_SNR_temp(:), corr_f_noback_NoRM_temp(:), corr_f_raw_SNR_temp(:),...
%     corr_f_raw_NoRM_temp(:), corr_f_noback_SNR_neuropil_temp(:), corr_f_noback_NoRM_neuropil_temp(:),...
%     corr_f_raw_SNR_neuropil_temp(:), corr_f_raw_NoRM_neuropil_temp(:), corr_f_nobak_neuropil_temp(:)],...
%     {'raw','no back','no neuropil','no back, SNR','no back, NoRM', 'raw, SNR',...
%     'raw, NoRM', 'no back, SNR, no neuropil', 'no back, NoRM, no neuropil',...
%     'raw, SNR, no neuropil', 'raw, NoRM, no neuropil', 'no back, no neuropil'});
% figure;
% c = multcompare(stats);

%%
surr_array = unique(data_surround);
for i_s = 1:length(surr_array)
    corr_f_raw_temp = corr_f_avg_raw(find(data_surround==surr_array(i_s)));
    corr_f_raw_neuropil_temp = corr_f_avg_neuropil_back(find(data_surround==surr_array(i_s)));
    corr_f_raw_SNR_temp = corr_f_avg_back_SNR(find(data_surround==surr_array(i_s)));
    corr_f_raw_SNR_neuropil_temp = corr_f_avg_neuropil_back_SNR(find(data_surround==surr_array(i_s)));
    corr_f_raw_NoRM01_temp = corr_f_avg_back_NoRM_01(find(data_surround==surr_array(i_s)));
    corr_f_raw_NoRM1_temp = corr_f_avg_back_NoRM_1(find(data_surround==surr_array(i_s)));
    corr_f_raw_NoRM_temp = corr_f_avg_back_NoRM(find(data_surround==surr_array(i_s)));
    corr_f_raw_NoRM01_neuropil_temp = corr_f_avg_neuropil_back_NoRM_01(find(data_surround==surr_array(i_s)));
    corr_f_raw_NoRM1_neuropil_temp = corr_f_avg_neuropil_back_NoRM_1(find(data_surround==surr_array(i_s)));
    corr_f_raw_NoRM_neuropil_temp = corr_f_avg_neuropil_back_NoRM(find(data_surround==surr_array(i_s)));
    corr_f_noback_temp = corr_f_avg_noback(find(data_surround==surr_array(i_s)));
    corr_f_noback_neuropil_temp = corr_f_avg_neuropil_noback(find(data_surround==surr_array(i_s)));
    corr_f_noback_SNR_temp = corr_f_avg_noback_SNR(find(data_surround==surr_array(i_s)));
    corr_f_noback_SNR_neuropil_temp = corr_f_avg_neuropil_noback_SNR(find(data_surround==surr_array(i_s)));
    corr_f_noback_NoRM01_temp = corr_f_avg_noback_NoRM_01(find(data_surround==surr_array(i_s)));
    corr_f_noback_NoRM1_temp = corr_f_avg_noback_NoRM_1(find(data_surround==surr_array(i_s)));
    corr_f_noback_NoRM_temp = corr_f_avg_noback_NoRM(find(data_surround==surr_array(i_s)));
    corr_f_noback_NoRM01_neuropil_temp = corr_f_avg_neuropil_noback_NoRM_01(find(data_surround==surr_array(i_s)));
    corr_f_noback_NoRM1_neuropil_temp = corr_f_avg_neuropil_noback_NoRM_1(find(data_surround==surr_array(i_s)));
    corr_f_noback_NoRM_neuropil_temp = corr_f_avg_neuropil_noback_NoRM(find(data_surround==surr_array(i_s)));

    array_exp = repmat([1:1:length(corr_f_raw_temp)]',1,20);
    corr_all = [corr_f_raw_temp(:); corr_f_noback_temp(:); corr_f_raw_neuropil_temp(:); ...
        corr_f_noback_SNR_temp(:); corr_f_noback_NoRM01_temp(:); corr_f_noback_NoRM1_temp(:);...
        corr_f_noback_NoRM_temp(:); corr_f_raw_SNR_temp(:); corr_f_raw_NoRM01_temp(:); corr_f_raw_NoRM1_temp(:);...
        corr_f_raw_NoRM_temp(:); corr_f_noback_SNR_neuropil_temp(:); corr_f_noback_NoRM01_neuropil_temp(:);...
        corr_f_noback_NoRM1_neuropil_temp(:); corr_f_noback_NoRM_neuropil_temp(:);...
        corr_f_raw_SNR_neuropil_temp(:); corr_f_raw_NoRM01_neuropil_temp(:);...
        corr_f_raw_NoRM1_neuropil_temp(:); corr_f_raw_NoRM_neuropil_temp(:); corr_f_noback_neuropil_temp(:)];
    back_subtr = repmat([0 1 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1],length(corr_f_raw_temp),1);
    SNR_corr = repmat([0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0],length(corr_f_raw_temp),1);
    NoRM01_corr = repmat([0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0],length(corr_f_raw_temp),1);
    NoRM1_corr = repmat([0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0],length(corr_f_raw_temp),1);
    NoRM_corr = repmat([0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0],length(corr_f_raw_temp),1);
    neuropil_corr = repmat([0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1],length(corr_f_raw_temp),1);
    
    array_exp = array_exp(:);
    corr_all = corr_all(:);
    back_subtr = back_subtr(:);
    SNR_corr = SNR_corr(:);
    NoRM01_corr = NoRM01_corr(:);
    NoRM1_corr = NoRM1_corr(:);
    NoRM_corr = NoRM_corr(:);
    neuropil_corr = neuropil_corr(:);
    
    tbl = table(corr_all, array_exp, back_subtr, SNR_corr, NoRM01_corr, NoRM1_corr,...
        NoRM_corr, neuropil_corr ,'VariableNames',{'SNR','exp','background','SNRcorr',...
        'NoRM01','NoRM1','NoRM','neuropil'});
%     lme = fitlme(tbl,'SNR ~ 1 + background + SNRcorr + NoRM01 + NoRM1 + NoRM + neuropil + (1|exp) + (background|exp) + (SNRcorr|exp) + (NoRM01|exp) + (NoRM1|exp) + (NoRM|exp) + (neuropil|exp)')
    lme = fitlme(tbl,'SNR ~ 1 + background + SNRcorr + NoRM01 + NoRM1 + NoRM + neuropil + (1+background+SNRcorr+NoRM01+NoRM1+NoRM+neuropil|exp)')
    beta = fixedEffects(lme);
    [~,~,STATS] = randomEffects(lme);
end

%%
surr_array = unique(data_surround);
for i_s = 1:length(surr_array)
    snr_f_raw_temp = snr_f_avg_raw(find(data_surround==surr_array(i_s)));
    snr_f_raw_neuropil_temp = snr_f_avg_neuropil_back(find(data_surround==surr_array(i_s)));
    snr_f_raw_SNR_temp = snr_f_avg_back_SNR(find(data_surround==surr_array(i_s)));
    snr_f_raw_SNR_neuropil_temp = snr_f_avg_neuropil_back_SNR(find(data_surround==surr_array(i_s)));
    snr_f_raw_NoRM01_temp = snr_f_avg_back_NoRM_01(find(data_surround==surr_array(i_s)));
    snr_f_raw_NoRM1_temp = snr_f_avg_back_NoRM_1(find(data_surround==surr_array(i_s)));
    snr_f_raw_NoRM_temp = snr_f_avg_back_NoRM(find(data_surround==surr_array(i_s)));
    snr_f_raw_NoRM01_neuropil_temp = snr_f_avg_neuropil_back_NoRM_01(find(data_surround==surr_array(i_s)));
    snr_f_raw_NoRM1_neuropil_temp = snr_f_avg_neuropil_back_NoRM_1(find(data_surround==surr_array(i_s)));
    snr_f_raw_NoRM_neuropil_temp = snr_f_avg_neuropil_back_NoRM(find(data_surround==surr_array(i_s)));
    snr_f_noback_temp = snr_f_avg_nobachk(find(data_surround==surr_array(i_s)));
    snr_f_noback_neuropil_temp = snr_f_avg_neuropil_noback(find(data_surround==surr_array(i_s)));
    snr_f_noback_SNR_temp = snr_f_avg_noback_SNR(find(data_surround==surr_array(i_s)));
    snr_f_noback_SNR_neuropil_temp = snr_f_avg_neuropil_noback_SNR(find(data_surround==surr_array(i_s)));
    snr_f_noback_NoRM01_temp = snr_f_avg_noback_NoRM_01(find(data_surround==surr_array(i_s)));
    snr_f_noback_NoRM1_temp = snr_f_avg_noback_NoRM_1(find(data_surround==surr_array(i_s)));
    snr_f_noback_NoRM_temp = snr_f_avg_noback_NoRM(find(data_surround==surr_array(i_s)));
    snr_f_noback_NoRM01_neuropil_temp = snr_f_avg_neuropil_noback_NoRM_01(find(data_surround==surr_array(i_s)));
    snr_f_noback_NoRM1_neuropil_temp = snr_f_avg_neuropil_noback_NoRM_1(find(data_surround==surr_array(i_s)));
    snr_f_noback_NoRM_neuropil_temp = stnr_f_avg_neuropil_noback_NoRM(find(data_surround==surr_array(i_s)));

    array_exp = repmat([1:1:length(snr_f_raw_temp)]',1,20);
    snr_all = [snr_f_raw_temp(:); snr_f_noback_temp(:); snr_f_raw_neuropil_temp(:); ...
        snr_f_noback_SNR_temp(:); snr_f_noback_NoRM01_temp(:); snr_f_noback_NoRM1_temp(:);...
        snr_f_noback_NoRM_temp(:); snr_f_raw_SNR_temp(:); snr_f_raw_NoRM01_temp(:); snr_f_raw_NoRM1_temp(:);...
        snr_f_raw_NoRM_temp(:); snr_f_noback_SNR_neuropil_temp(:); snr_f_noback_NoRM01_neuropil_temp(:);...
        snr_f_noback_NoRM1_neuropil_temp(:); snr_f_noback_NoRM_neuropil_temp(:);...
        snr_f_raw_SNR_neuropil_temp(:); snr_f_raw_NoRM01_neuropil_temp(:);...
        snr_f_raw_NoRM1_neuropil_temp(:); snr_f_raw_NoRM_neuropil_temp(:); snr_f_noback_neuropil_temp(:)];
    back_subtr = repmat([0 1 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1],length(snr_f_raw_temp),1);
    SNR_snr = repmat([0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0],length(snr_f_raw_temp),1);
    NoRM01_snr = repmat([0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0],length(snr_f_raw_temp),1);
    NoRM1_snr = repmat([0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0],length(snr_f_raw_temp),1);
    NoRM_snr = repmat([0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0],length(snr_f_raw_temp),1);
    neuropil_snr = repmat([0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1],length(snr_f_raw_temp),1);
    
    array_exp = array_exp(:);
    snr_all = snr_all(:);
    back_subtr = back_subtr(:);
    SNR_snr = SNR_snr(:);
    NoRM01_snr = NoRM01_snr(:);
    NoRM1_snr = NoRM1_snr(:);
    NoRM_snr = NoRM_snr(:);
    neuropil_snr = neuropil_snr(:);g
    
    tbl = table(snr_all, array_exp, back_subtr, SNR_snr, NoRM01_snr, NoRM1_snr,...
        NoRM_snr, neuropil_snr ,'VariableNames',{'SNR','exp','background','SNRsnr',...
        'NoRM01','NoRM1','NoRM','neuropil'});
%     lme = fitlme(tbl,'SNR ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + (1|exp) + (background|exp) + (SNRsnr|exp) + (NoRM01|exp) + (NoRM1|exp) + (NoRM|exp) + (neuropil|exp)')
    lme = fitlme(tbl,'SNR ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + (1+background+SNRsnr+NoRM01+NoRM1+NoRM+neuropil|exp)')
    lme = fitlm(tbl,'SNR ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + background:SNRsnr + background:NoRM01 + background:NoRM1 + background:NoRM + background:neuropil + background:SNRsnr:neuropil + background:NoRM01:neuropil + background:NoRM1:neuropil + background:NoRM:neuropil + SNRsnr:neuropil + NoRM01:neuropil + NoRM1*neuropil + NoRM*neuropil + (1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + background:SNRsnr + background:NoRM01 + background:NoRM1 + background:NoRM + background:neuropil + background:SNRsnr:neuropil + background*NoRM01*neuropil + background:NoRM1:neuropil + background:NoRM:neuropil + SNRsnr:neuropil + NoRM01:neuropil + NoRM1:neuropil + NoRM:neuropil | exp)')
    beta = fixedEffects(lme);
    [~,~,STATS] = randomEffects(lme);
    
    tbl = table(snr_all, array_exp, back_subtr, SNR_snr, NoRM01_snr, NoRM1_snr,...
        NoRM_snr, neuropil_snr , back_subtr.*SNR_snr, back_subtr.*NoRM01_snr, back_subtr.*NoRM1_snr,...
        back_subtr.*NoRM_snr, back_subtr.*neuropil_snr, SNR_snr.*neuropil_snr, NoRM01_snr.*neuropil_snr, NoRM1_snr.*neuropil_snr,...
        NoRM_snr.*neuropil_snr, back_subtr.*SNR_snr.*neuropil_snr, back_subtr.*NoRM01_snr.*neuropil_snr, back_subtr.*NoRM1_snr.*neuropil_snr,...
        back_subtr.*NoRM_snr.*neuropil_snr,'VariableNames',{'SNR','exp','background','SNRsnr',...
        'NoRM01','NoRM1','NoRM','neuropil','back_SNRsnr',...
        'back_NoRM01','back_NoRM1','back_NoRM','back_neuropil','SNRsnr_neuropil',...
        'NoRM01_neuropil','NoRM1_neuropil','NoRM_neuropil','back_SNRsnr_neuropil',...
        'back_NoRM01_neuropil','back_NoRM1_neuropil','back_NoRM_neuropil'});
    lme = fitlme(tbl,'SNR ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + back_SNRsnr+ back_NoRM01 + back_NoRM1 + back_NoRM + back_neuropil + SNRsnr_neuropil + NoRM01_neuropil + NoRM1_neuropil + NoRM_neuropil + back_SNRsnr_neuropil + back_NoRM01_neuropil + back_NoRM1_neuropil + back_NoRM_neuropil + (1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + back_SNRsnr+ back_NoRM01 + back_NoRM1 + back_NoRM + back_neuropil + SNRsnr_neuropil + NoRM01_neuropil + NoRM1_neuropil + NoRM_neuropil + back_SNRsnr_neuropil + back_NoRM01_neuropil + back_NoRM1_neuropil + back_NoRM_neuropil|exp)')
    beta = fixedEffects(lme);
    [~,~,STATS] = randomEffects(lme);
    
    figure;
    n_pred = 20;
    for i1 = 1:n_pred
        hold on;
        plot(i1*ones(1,length(snr_f_raw_temp)),beta(i1) + STATS.Estimate(i1:n_pred:length(STATS.Estimate)),'*');
    end
    hold on; plot(1:1:n_pred,beta,'k*');
    
    
    tbl2 = table(snr_all, back_subtr, SNR_snr, NoRM01_snr, NoRM1_snr,...
        NoRM_snr, neuropil_snr ,'VariableNames',{'SNR','background','SNRsnr',...
        'NoRM01','NoRM1','NoRM','neuropil'});
    fitlm(tbl2,'SNR ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + background:SNRsnr + background:NoRM01 + background*NoRM1 + background:NoRM + background:neuropil + background:SNRsnr:neuropil + background:NoRM01:neuropil + background:NoRM1:neuropil + background:NoRM:neuropil + SNRsnr:neuropil + NoRM01:neuropil + NoRM1:neuropil + NoRM:neuropil')
end

%%
array_exp = repmat([1:1:length(corr_f_avg_raw(id_keep_def))]',1,20);
array_surr = repmat(data_surround,1,20);
corr_all = [corr_f_avg_raw(1:length(id_keep_def)); corr_f_avg_noback(1:length(id_keep_def)); ...
    corr_f_avg_neuropil_back(1:length(id_keep_def)); corr_f_avg_noback_SNR(1:length(id_keep_def));...
    corr_f_avg_noback_NoRM_01(1:length(id_keep_def)); corr_f_avg_noback_NoRM_1(1:length(id_keep_def));...
    corr_f_avg_noback_NoRM(1:length(id_keep_def)); corr_f_avg_back_SNR(1:length(id_keep_def));...
    corr_f_avg_back_NoRM_01(1:length(id_keep_def)); corr_f_avg_back_NoRM_1(1:length(id_keep_def));...
    corr_f_avg_back_NoRM(1:length(id_keep_def)); corr_f_avg_neuropil_noback_SNR(1:length(id_keep_def));...
    corr_f_avg_neuropil_noback_NoRM_01(1:length(id_keep_def)); corr_f_avg_neuropil_noback_NoRM_1(1:length(id_keep_def));...
    corr_f_avg_neuropil_noback_NoRM(1:length(id_keep_def)); corr_f_avg_neuropil_back_SNR(1:length(id_keep_def));...
    corr_f_avg_neuropil_back_NoRM_01(1:length(id_keep_def)); corr_f_avg_neuropil_back_NoRM_1(1:length(id_keep_def));...
    corr_f_avg_neuropil_back_NoRM(1:length(id_keep_def)); corr_f_avg_neuropil_noback(1:length(id_keep_def))];
back_subtr = repmat([0 1 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1],length(corr_f_avg_raw(id_keep_def)),1);
SNR_corr = repmat([0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0],length(corr_f_avg_raw(id_keep_def)),1);
NoRM01_corr = repmat([0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0],length(corr_f_avg_raw(id_keep_def)),1);
NoRM1_corr = repmat([0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0],length(corr_f_avg_raw(id_keep_def)),1);
NoRM_corr = repmat([0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0],length(corr_f_avg_raw(id_keep_def)),1);
neuropil_corr = repmat([0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1],length(corr_f_avg_raw(id_keep_def)),1);

array_exp = array_exp(:);
array_surr = array_surr(:);
corr_all = corr_all(:);
back_subtr = back_subtr(:);
SNR_corr = SNR_corr(:);
NoRM01_corr = NoRM01_corr(:);
NoRM1_corr = NoRM1_corr(:);
NoRM_corr = NoRM_corr(:);
neuropil_corr = neuropil_corr(:);

tbl = table(corr_all, array_exp, back_subtr, SNR_corr, NoRM01_corr, NoRM1_corr,...
    NoRM_corr, neuropil_corr , back_subtr.*SNR_corr, back_subtr.*NoRM01_corr, back_subtr.*NoRM1_corr,...
    back_subtr.*NoRM_corr, back_subtr.*neuropil_corr, SNR_corr.*neuropil_corr, NoRM01_corr.*neuropil_corr, NoRM1_corr.*neuropil_corr,...
    NoRM_corr.*neuropil_corr, back_subtr.*SNR_corr.*neuropil_corr, back_subtr.*NoRM01_corr.*neuropil_corr, back_subtr.*NoRM1_corr.*neuropil_corr,...
    back_subtr.*NoRM_corr.*neuropil_corr,'VariableNames',{'SNR','exp','background','SNRsnr',...
    'NoRM01','NoRM1','NoRM','neuropil','back_SNRsnr',...
    'back_NoRM01','back_NoRM1','back_NoRM','back_neuropil','SNRsnr_neuropil',...
    'NoRM01_neuropil','NoRM1_neuropil','NoRM_neuropil','back_SNRsnr_neuropil',...
    'back_NoRM01_neuropil','back_NoRM1_neuropil','back_NoRM_neuropil'});
% lme = fitlme(tbl,'SNR ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + back_SNRsnr+ back_NoRM01 + back_NoRM1 + back_NoRM + back_neuropil + SNRsnr_neuropil + NoRM01_neuropil + NoRM1_neuropil + NoRM_neuropil + back_SNRsnr_neuropil + back_NoRM01_neuropil + back_NoRM1_neuropil + back_NoRM_neuropil + (1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + back_SNRsnr+ back_NoRM01 + back_NoRM1 + back_NoRM + back_neuropil + SNRsnr_neuropil + NoRM01_neuropil + NoRM1_neuropil + NoRM_neuropil + back_SNRsnr_neuropil + back_NoRM01_neuropil + back_NoRM1_neuropil + back_NoRM_neuropil|exp)')
lme = fitlme(tbl,'SNR ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + back_SNRsnr+ back_NoRM01 + back_NoRM1 + back_NoRM + back_neuropil + SNRsnr_neuropil + NoRM01_neuropil + NoRM1_neuropil + NoRM_neuropil + back_SNRsnr_neuropil + back_NoRM01_neuropil + back_NoRM1_neuropil + back_NoRM_neuropil + (1|exp)')
beta = fixedEffects(lme);
[~,~,STATS] = randomEffects(lme);

tbl = table(array_surr, back_subtr, SNR_corr, NoRM01_corr, NoRM1_corr,...
    NoRM_corr, neuropil_corr,corr_all ,'VariableNames',{'surround','background','SNRcorr',...
    'NoRM01','NoRM1','NoRM','neuropil','pair_corr'});
fitlm(tbl,'interactions')

%%
id_keep_def2 = id_keep_def(find(data_surround<=1));

array_exp = repmat([1:1:length(snr_f_avg_raw(id_keep_def2))]',1,20);
array_surr = repmat(data_surround(find(data_surround<=1)),1,20);
snr_all = [snr_f_avg_raw(1:length(id_keep_def2)); snr_f_avg_noback(1:length(id_keep_def2)); ...
    snr_f_avg_neuropil_back(1:length(id_keep_def2)); snr_f_avg_noback_SNR(1:length(id_keep_def2));...
    snr_f_avg_noback_NoRM_01(1:length(id_keep_def2)); snr_f_avg_noback_NoRM_1(1:length(id_keep_def2));...
    snr_f_avg_noback_NoRM(1:length(id_keep_def2)); snr_f_avg_back_SNR(1:length(id_keep_def2));...
    snr_f_avg_back_NoRM_01(1:length(id_keep_def2)); snr_f_avg_back_NoRM_1(1:length(id_keep_def2));...
    snr_f_avg_back_NoRM(1:length(id_keep_def2)); snr_f_avg_neuropil_noback_SNR(1:length(id_keep_def2));...
    snr_f_avg_neuropil_noback_NoRM_01(1:length(id_keep_def2)); snr_f_avg_neuropil_noback_NoRM_1(1:length(id_keep_def2));...
    snr_f_avg_neuropil_noback_NoRM(1:length(id_keep_def2)); snr_f_avg_neuropil_back_SNR(1:length(id_keep_def2));...
    snr_f_avg_neuropil_back_NoRM_01(1:length(id_keep_def2)); snr_f_avg_neuropil_back_NoRM_1(1:length(id_keep_def2));...
    snr_f_avg_neuropil_back_NoRM(1:length(id_keep_def2)); snr_f_avg_neuropil_noback(1:length(id_keep_def2))];
corr_all = [corr_f_avg_raw(1:length(id_keep_def2)); corr_f_avg_noback(1:length(id_keep_def2)); ...
    corr_f_avg_neuropil_back(1:length(id_keep_def2)); corr_f_avg_noback_SNR(1:length(id_keep_def2));...
    corr_f_avg_noback_NoRM_01(1:length(id_keep_def2)); corr_f_avg_noback_NoRM_1(1:length(id_keep_def2));...
    corr_f_avg_noback_NoRM(1:length(id_keep_def2)); corr_f_avg_back_SNR(1:length(id_keep_def2));...
    corr_f_avg_back_NoRM_01(1:length(id_keep_def2)); corr_f_avg_back_NoRM_1(1:length(id_keep_def2));...
    corr_f_avg_back_NoRM(1:length(id_keep_def2)); corr_f_avg_neuropil_noback_SNR(1:length(id_keep_def2));...
    corr_f_avg_neuropil_noback_NoRM_01(1:length(id_keep_def2)); corr_f_avg_neuropil_noback_NoRM_1(1:length(id_keep_def2));...
    corr_f_avg_neuropil_noback_NoRM(1:length(id_keep_def2)); corr_f_avg_neuropil_back_SNR(1:length(id_keep_def2));...
    corr_f_avg_neuropil_back_NoRM_01(1:length(id_keep_def2)); corr_f_avg_neuropil_back_NoRM_1(1:length(id_keep_def2));...
    corr_f_avg_neuropil_back_NoRM(1:length(id_keep_def2)); corr_f_avg_neuropil_noback(1:length(id_keep_def2))];
back_subtr = repmat([0 1 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1],length(snr_f_avg_raw(id_keep_def2)),1);
SNR_snr = repmat([0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0],length(snr_f_avg_raw(id_keep_def2)),1);
NoRM01_snr = repmat([0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0],length(snr_f_avg_raw(id_keep_def2)),1);
NoRM1_snr = repmat([0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0],length(snr_f_avg_raw(id_keep_def2)),1);
NoRM_snr = repmat([0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0],length(snr_f_avg_raw(id_keep_def2)),1);
neuropil_snr = repmat([0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1],length(snr_f_avg_raw(id_keep_def2)),1);

array_exp = array_exp(:);
array_surr = array_surr(:);
snr_all = snr_all(:);
corr_all = corr_all(:);
back_subtr = back_subtr(:);
SNR_snr = SNR_snr(:);
NoRM01_snr = NoRM01_snr(:);
NoRM1_snr = NoRM1_snr(:);
NoRM_snr = NoRM_snr(:);
neuropil_snr = neuropil_snr(:);

% tbl = table(snr_all, array_exp, back_subtr, SNR_snr, NoRM01_snr, NoRM1_snr,...
%     NoRM_snr, neuropil_snr , back_subtr.*SNR_snr, back_subtr.*NoRM01_snr, back_subtr.*NoRM1_snr,...
%     back_subtr.*NoRM_snr, back_subtr.*neuropil_snr, SNR_snr.*neuropil_snr, NoRM01_snr.*neuropil_snr, NoRM1_snr.*neuropil_snr,...
%     NoRM_snr.*neuropil_snr, back_subtr.*SNR_snr.*neuropil_snr, back_subtr.*NoRM01_snr.*neuropil_snr, back_subtr.*NoRM1_snr.*neuropil_snr,...
%     back_subtr.*NoRM_snr.*neuropil_snr,'VariableNames',{'SNR','exp','background','SNRsnr',...
%     'NoRM01','NoRM1','NoRM','neuropil','back_SNRsnr',...
%     'back_NoRM01','back_NoRM1','back_NoRM','back_neuropil','SNRsnr_neuropil',...
%     'NoRM01_neuropil','NoRM1_neuropil','NoRM_neuropil','back_SNRsnr_neuropil',...
%     'back_NoRM01_neuropil','back_NoRM1_neuropil','back_NoRM_neuropil'});
% % lme = fitlme(tbl,'SNR ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + back_SNRsnr+ back_NoRM01 + back_NoRM1 + back_NoRM + back_neuropil + SNRsnr_neuropil + NoRM01_neuropil + NoRM1_neuropil + NoRM_neuropil + back_SNRsnr_neuropil + back_NoRM01_neuropil + back_NoRM1_neuropil + back_NoRM_neuropil + (1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + back_SNRsnr+ back_NoRM01 + back_NoRM1 + back_NoRM + back_neuropil + SNRsnr_neuropil + NoRM01_neuropil + NoRM1_neuropil + NoRM_neuropil + back_SNRsnr_neuropil + back_NoRM01_neuropil + back_NoRM1_neuropil + back_NoRM_neuropil|exp)')
% lme = fitlme(tbl,'SNR ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + back_SNRsnr+ back_NoRM01 + back_NoRM1 + back_NoRM + back_neuropil + SNRsnr_neuropil + NoRM01_neuropil + NoRM1_neuropil + NoRM_neuropil + back_SNRsnr_neuropil + back_NoRM01_neuropil + back_NoRM1_neuropil + back_NoRM_neuropil + (1|exp)')
% beta = fixedEffects(lme);
% [~,~,STATS] = randomEffects(lme);
%%
tbl_snr = table(array_exp,back_subtr, SNR_snr, NoRM01_snr, NoRM1_snr,...
    NoRM_snr, neuropil_snr,snr_all ,'VariableNames',{'exp','background','SNRsnr',...
    'NoRM01','NoRM1','NoRM','neuropil','SNR'});
% fitlm(tbl_snr,'SNR ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + background*SNRsnr + background*NoRM01 + background*NoRM1 + background*NoRM + background*neuropil + background*SNRsnr*neuropil + background*NoRM01*neuropil + background*NoRM1*neuropil + background*NoRM*neuropil + SNRsnr*neuropil + NoRM01*neuropil + NoRM1*neuropil + NoRM*neuropil')
stepwise_snr_model = stepwiselm(tbl_snr(:,2:end),'SNR ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + background*SNRsnr + background*NoRM01 + background*NoRM1 + background*NoRM + background*neuropil + background*SNRsnr*neuropil + background*NoRM01*neuropil + background*NoRM1*neuropil + background*NoRM*neuropil + SNRsnr*neuropil + NoRM01*neuropil + NoRM1*neuropil + NoRM*neuropil')
% stepwiselm(tbl_snr(:,2:end),'SNR ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil')
% stepwiselm(tbl_snr(:,2:end),'interactions')


tbl_corr = table(array_exp, back_subtr, SNR_snr, NoRM01_snr, NoRM1_snr,...
    NoRM_snr, neuropil_snr,corr_all ,'VariableNames',{'exp','background','SNRsnr',...
    'NoRM01','NoRM1','NoRM','neuropil','pair_corr'});
% fitlm(tbl_corr(:,2:end),'pair_corr ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + background*SNRsnr + background*NoRM01 + background*NoRM1 + background*NoRM + background*neuropil + background*SNRsnr*neuropil + background*NoRM01*neuropil + background*NoRM1*neuropil + background*NoRM*neuropil + SNRsnr*neuropil + NoRM01*neuropil + NoRM1*neuropil + NoRM*neuropil')
stepwise_corr_model = stepwiselm(tbl_corr(:,2:end),'pair_corr ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + background*SNRsnr + background*NoRM01 + background*NoRM1 + background*NoRM + background*neuropil + background*SNRsnr*neuropil + background*NoRM01*neuropil + background*NoRM1*neuropil + background*NoRM*neuropil + SNRsnr*neuropil + NoRM01*neuropil + NoRM1*neuropil + NoRM*neuropil')
% stepwiselm(tbl_corr(:,2:end),'pair_corr ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil')
% stepwiselm(tbl_corr(:,2:end),'interactions')
% stepwiselm(tbl_corr(:,2:end),'constant')
% lme = fitlme(tbl_corr,'pair_corr ~ 1 + background + SNRsnr + NoRM01 + NoRM1 + NoRM + neuropil + background*SNRsnr + background*NoRM01 + background*NoRM1 + background*NoRM + background*neuropil + background*SNRsnr*neuropil + background*NoRM01*neuropil + background*NoRM1*neuropil + background*NoRM*neuropil + SNRsnr*neuropil + NoRM01*neuropil + NoRM1*neuropil + NoRM*neuropil + (1|exp)')
% beta = fixedEffects(lme);
% [~,~,STATS] = randomEffects(lme);

