save_path_0 = '/media/DATA/mmoroni/software_sls_project/analyses/';
%% initialize data
csv_data = '../data/data_table_server.csv';
data_surround_0 = readmatrix(csv_data,'Range','F:F','OutputType','double');
animal_state_0 = readmatrix(csv_data,'Range','B:B','OutputType','string');
ref_ROIs_0 = readmatrix(csv_data,'Range','I:I','OutputType','string');

anesthetized = 0; %flag to analyze awake/anesthetized animals data
%filter data
if anesthetized == 1
    id_keep = find(animal_state_0 == 'anesthetized/');
    save_path = [save_path_0 'anesthetized/'];
else
    id_keep = find(animal_state_0 == 'awake/');
    save_path = [save_path_0 'awake/'];
end
data_surround = data_surround_0(id_keep);
ref_ROIs = ref_ROIs_0(id_keep);

%keep only with reference segmentation
id_keep2 = find(1-ismissing(ref_ROIs));
data_surround = data_surround(id_keep2);


%% import analyses results

if anesthetized == 1
    [time_neuropil_noback, time_neuropil_noback_SNR, time_neuropil_noback_NoRM,...
        snr_f_avg_noback, snr_f_avg_neuropil_noback, snr_f_avg_noback_SNR,...
        snr_f_avg_neuropil_noback_SNR, snr_f_avg_noback_NoRM,...
        snr_f_avg_neuropil_noback_NoRM, snr_ca_avg_noback, snr_ca_avg_neuropil_noback,...
        snr_ca_avg_noback_SNR, snr_ca_avg_neuropil_noback_SNR, snr_ca_avg_noback_NoRM, ...
        snr_ca_avg_neuropil_noback_NoRM, corr_f_avg_raw, corr_f_avg_noback,...
        corr_f_avg_neuropil_noback, corr_f_avg_noback_SNR, corr_f_avg_neuropil_noback_SNR,...
        corr_f_avg_noback_NoRM, corr_f_avg_neuropil_noback_NoRM, corr_ca_avg_raw,...
        corr_ca_avg_noback, corr_ca_avg_neuropil_noback, corr_ca_avg_noback_SNR,...
        corr_ca_avg_neuropil_noback_SNR, corr_ca_avg_noback_NoRM, corr_ca_avg_neuropil_noback_NoRM] =...
        import_neuropil_analyses([save_path_0 'anesthetized_neuropil_summary.csv']);
    
    
    [time_neuropil_back, time_neuropil_back_SNR, time_neuropil_back_NoRM, snr_f_avg_raw,...
        snr_f_avg_neuropil_raw, snr_f_avg_raw_SNR, snr_f_avg_neuropil_raw_SNR, ...
        snr_f_avg_raw_NoRM, snr_f_avg_neuropil_raw_NoRM, snr_ca_avg_raw, ...
        snr_ca_avg_neuropil_raw, snr_ca_avg_raw_SNR, snr_ca_avg_neuropil_raw_SNR,...
        snr_ca_avg_raw_NoRM, snr_ca_avg_neuropil_raw_NoRM, corr_f_avg_raw,...
        corr_f_avg_neuropil_raw, corr_f_avg_raw_SNR, corr_f_avg_neuropil_raw_SNR,...
        corr_f_avg_raw_NoRM, corr_f_avg_neuropil_raw_NoRM, corr_ca_avg_raw, ...
        corr_ca_avg_neuropil_raw, corr_ca_avg_raw_SNR, corr_ca_avg_neuropil_raw_SNR,...
        corr_ca_avg_raw_NoRM, corr_ca_avg_neuropil_raw_NoRM] = ...
        import_neuropil_withback_analyses([save_path_0 'anesthetized_withback_neuropil_summary.csv']);
else
    [time_neuropil_noback, time_neuropil_noback_SNR, time_neuropil_noback_NoRM,...
        snr_f_avg_noback, snr_f_avg_neuropil_noback, snr_f_avg_noback_SNR,...
        snr_f_avg_neuropil_noback_SNR, snr_f_avg_noback_NoRM,...
        snr_f_avg_neuropil_noback_NoRM, snr_ca_avg_noback, snr_ca_avg_neuropil_noback,...
        snr_ca_avg_noback_SNR, snr_ca_avg_neuropil_noback_SNR, snr_ca_avg_noback_NoRM, ...
        snr_ca_avg_neuropil_noback_NoRM, corr_f_avg_raw, corr_f_avg_noback,...
        corr_f_avg_neuropil_noback, corr_f_avg_noback_SNR, corr_f_avg_neuropil_noback_SNR,...
        corr_f_avg_noback_NoRM, corr_f_avg_neuropil_noback_NoRM, corr_ca_avg_raw,...
        corr_ca_avg_noback, corr_ca_avg_neuropil_noback, corr_ca_avg_noback_SNR,...
        corr_ca_avg_neuropil_noback_SNR, corr_ca_avg_noback_NoRM, corr_ca_avg_neuropil_noback_NoRM] =...
        import_neuropil_analyses([save_path_0 'awake_neuropil_summary.csv']);
    
    [time_neuropil_back, time_neuropil_back_SNR, time_neuropil_back_NoRM, snr_f_avg_raw,...
        snr_f_avg_neuropil_raw, snr_f_avg_raw_SNR, snr_f_avg_neuropil_raw_SNR, ...
        snr_f_avg_raw_NoRM, snr_f_avg_neuropil_raw_NoRM, snr_ca_avg_raw, ...
        snr_ca_avg_neuropil_raw, snr_ca_avg_raw_SNR, snr_ca_avg_neuropil_raw_SNR,...
        snr_ca_avg_raw_NoRM, snr_ca_avg_neuropil_raw_NoRM, corr_f_avg_raw,...
        corr_f_avg_neuropil_raw, corr_f_avg_raw_SNR, corr_f_avg_neuropil_raw_SNR,...
        corr_f_avg_raw_NoRM, corr_f_avg_neuropil_raw_NoRM, corr_ca_avg_raw, ...
        corr_ca_avg_neuropil_raw, corr_ca_avg_raw_SNR, corr_ca_avg_neuropil_raw_SNR,...
        corr_ca_avg_raw_NoRM, corr_ca_avg_neuropil_raw_NoRM] = ...
        import_neuropil_withback_analyses([save_path_0 'awake_withback_neuropil_summary.csv']);
end

data_surround(data_surround>=3)=3;

%% all pipelines SNR

box_plot_snr = figure; 
surr_array = unique(data_surround);
for i_s = 1:length(surr_array)
    snr_f_raw_temp = snr_f_avg_raw(find(data_surround==surr_array(i_s)));
    snr_f_raw_neuropil_temp = snr_f_avg_neuropil_raw(find(data_surround==surr_array(i_s)));
    snr_f_raw_SNR_temp = snr_f_avg_raw_SNR(find(data_surround==surr_array(i_s)));
    snr_f_raw_SNR_neuropil_temp = snr_f_avg_neuropil_raw_SNR(find(data_surround==surr_array(i_s)));
    snr_f_raw_NoRM_temp = snr_f_avg_raw_NoRM(find(data_surround==surr_array(i_s)));
    snr_f_raw_NoRM_neuropil_temp = snr_f_avg_neuropil_raw_NoRM(find(data_surround==surr_array(i_s)));
    snr_f_noback_temp = snr_f_avg_noback(find(data_surround==surr_array(i_s)));
    snr_f_nobak_neuropil_temp = snr_f_avg_neuropil_noback(find(data_surround==surr_array(i_s)));
    snr_f_noback_SNR_temp = snr_f_avg_noback_SNR(find(data_surround==surr_array(i_s)));
    snr_f_noback_SNR_neuropil_temp = snr_f_avg_neuropil_noback_SNR(find(data_surround==surr_array(i_s)));
    snr_f_noback_NoRM_temp = snr_f_avg_noback_NoRM(find(data_surround==surr_array(i_s)));
    snr_f_noback_NoRM_neuropil_temp = snr_f_avg_neuropil_noback_NoRM(find(data_surround==surr_array(i_s)));
    figure(box_plot_snr)
    subplot(2,2,i_s);
    hold on; boxplot([snr_f_raw_temp(:), snr_f_noback_temp(:), snr_f_raw_neuropil_temp(:), ...
        snr_f_noback_SNR_temp(:), snr_f_noback_NoRM_temp(:), snr_f_raw_SNR_temp(:),...
        snr_f_raw_NoRM_temp(:), snr_f_noback_SNR_neuropil_temp(:), snr_f_noback_NoRM_neuropil_temp(:),...
        snr_f_raw_SNR_neuropil_temp(:), snr_f_raw_NoRM_neuropil_temp(:), snr_f_nobak_neuropil_temp(:)],...
        'Labels',{'raw','no back','no neuropil','no back, SNR','no back, NoRM', 'raw, SNR',...
        'raw, NoRM', 'no back, SNR, no neuropil', 'no back, NoRM, no neuropil',...
        'raw, SNR, no neuropil', 'raw, NoRM, no neuropil', 'no back, no neuropil'},...
        'PlotStyle','traditional','orientation','horizontal','DataLim',[0 80]);
    ylabel('SNR fluo');
    title(['surround=' num2str(surr_array(i_s))]);
    [p,tbl,stats] = kruskalwallis([snr_f_raw_temp(:), snr_f_noback_temp(:), snr_f_raw_neuropil_temp(:), ...
    snr_f_noback_SNR_temp(:), snr_f_noback_NoRM_temp(:), snr_f_raw_SNR_temp(:),...
    snr_f_raw_NoRM_temp(:), snr_f_noback_SNR_neuropil_temp(:), snr_f_noback_NoRM_neuropil_temp(:),...
    snr_f_raw_SNR_neuropil_temp(:), snr_f_raw_NoRM_neuropil_temp(:), snr_f_nobak_neuropil_temp(:)],...
    {'raw','no back','no neuropil','no back, SNR','no back, NoRM', 'raw, SNR',...
    'raw, NoRM', 'no back, SNR, no neuropil', 'no back, NoRM, no neuropil',...
    'raw, SNR, no neuropil', 'raw, NoRM, no neuropil', 'no back, no neuropil'});
    figure;
    c = multcompare(stats);
    title(['SNR. surround=' num2str(surr_array(i_s))]);
end

%% all pipelines CORR
box_plot_corr = figure;
surr_array = unique(data_surround);
for i_s = 1:length(surr_array)
    corr_f_raw_temp = corr_f_avg_raw(find(data_surround==surr_array(i_s)));
    corr_f_raw_neuropil_temp = corr_f_avg_neuropil_raw(find(data_surround==surr_array(i_s)));
    corr_f_raw_SNR_temp = corr_f_avg_raw_SNR(find(data_surround==surr_array(i_s)));
    corr_f_raw_SNR_neuropil_temp = corr_f_avg_neuropil_raw_SNR(find(data_surround==surr_array(i_s)));
    corr_f_raw_NoRM_temp = corr_f_avg_raw_NoRM(find(data_surround==surr_array(i_s)));
    corr_f_raw_NoRM_neuropil_temp = corr_f_avg_neuropil_raw_NoRM(find(data_surround==surr_array(i_s)));
    corr_f_noback_temp = corr_f_avg_noback(find(data_surround==surr_array(i_s)));
    corr_f_nobak_neuropil_temp = corr_f_avg_neuropil_noback(find(data_surround==surr_array(i_s)));
    corr_f_noback_SNR_temp = corr_f_avg_noback_SNR(find(data_surround==surr_array(i_s)));
    corr_f_noback_SNR_neuropil_temp = corr_f_avg_neuropil_noback_SNR(find(data_surround==surr_array(i_s)));
    corr_f_noback_NoRM_temp = corr_f_avg_noback_NoRM(find(data_surround==surr_array(i_s)));
    corr_f_noback_NoRM_neuropil_temp = corr_f_avg_neuropil_noback_NoRM(find(data_surround==surr_array(i_s)));
    figure(box_plot_corr);
    subplot(2,2,i_s);
    hold on; boxplot([corr_f_raw_temp(:), corr_f_noback_temp(:), corr_f_raw_neuropil_temp(:), ...
        corr_f_noback_SNR_temp(:), corr_f_noback_NoRM_temp(:), corr_f_raw_SNR_temp(:),...
        corr_f_raw_NoRM_temp(:), corr_f_noback_SNR_neuropil_temp(:), corr_f_noback_NoRM_neuropil_temp(:),...
        corr_f_raw_SNR_neuropil_temp(:), corr_f_raw_NoRM_neuropil_temp(:), corr_f_nobak_neuropil_temp(:)],...
        'Labels',{'raw','no back','no neuropil','no back, SNR','no back, NoRM', 'raw, SNR',...
        'raw, NoRM', 'no back, SNR, no neuropil', 'no back, NoRM, no neuropil',...
        'raw, SNR, no neuropil', 'raw, NoRM, no neuropil', 'no back, no neuropil'},...
        'PlotStyle','traditional','orientation','horizontal','DataLim',[0 1]);
    ylabel('corr fluo');
    title(['surround=' num2str(surr_array(i_s))]);
    [p,tbl,stats] = kruskalwallis([corr_f_raw_temp(:), corr_f_noback_temp(:), corr_f_raw_neuropil_temp(:), ...
        corr_f_noback_SNR_temp(:), corr_f_noback_NoRM_temp(:), corr_f_raw_SNR_temp(:),...
        corr_f_raw_NoRM_temp(:), corr_f_noback_SNR_neuropil_temp(:), corr_f_noback_NoRM_neuropil_temp(:),...
        corr_f_raw_SNR_neuropil_temp(:), corr_f_raw_NoRM_neuropil_temp(:), corr_f_nobak_neuropil_temp(:)],...
        {'raw','no back','no neuropil','no back, SNR','no back, NoRM', 'raw, SNR',...
        'raw, NoRM', 'no back, SNR, no neuropil', 'no back, NoRM, no neuropil',...
        'raw, SNR, no neuropil', 'raw, NoRM, no neuropil', 'no back, no neuropil'});
    figure;
    c = multcompare(stats);
    title(['CORR. surround=' num2str(surr_array(i_s))]);
end
